changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - duplicate
  categories:
    - title: 🚀 新增功能
      labels:
        - feature
        - enhancement
        - feat
    - title: 🐛 錯誤修正
      labels:
        - bug
        - fix
        - bugfix
    - title: 📚 文件更新
      labels:
        - documentation
        - docs
        - doc
    - title: 🔧 維護作業
      labels:
        - chore
        - maintenance
        - refactor
    - title: 其他變更
      labels:
        - "*"
