services:
  app:
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --workers
      - "4"
      - --proxy-headers
      - --loop
      - uvloop
    environment:
      - ENV=production
    container_name: wea-app-prod
    restart: always
    volumes:
      - ./logs:/code/logs # Bind mount logs directory (比照 dev)
  db:
    container_name: wea-db-prod
    restart: always
    volumes:
      - wea-db-data-prod:/var/lib/postgresql/data

volumes:
  wea-db-data-prod:
    external: true
