services:
  app:
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    environment:
      - ENV=production
    container_name: wea-app-prod
    restart: unless-stopped
  db:
    container_name: wea-db-prod
    restart: unless-stopped
    volumes:
      - wea-db-data-prod:/var/lib/postgresql/data

volumes:
  wea-db-data-prod:
    external: true
