services:
  app:
    command:
      - uvicorn
      - app.main:app
      - --port
      - "8000"
      - --reload
    volumes:
      - .:/code
      # Critical: Use a named volume to isolate the container's virtual environment
      # The local .venv would be mounted into the container with .:/code
      # Local .venv executables have host-specific shebangs, which are incompatible with the container
      # A named volume ensures the container uses its own, correctly built virtual environment
      - app-venv-dev:/code/.venv
      - ./logs:/code/logs # Bind mount logs directory
    environment:
      - ENV=development
    container_name: wea-app-dev
  db:
    container_name: wea-db-dev
    volumes:
      - wea-db-data-dev:/var/lib/postgresql/data

volumes:
  app-venv-dev:
  wea-db-data-dev:
