services:
  app:
    build:
      args:
        DEV: "true"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app
      - /app/.venv # Exclude overriding the virtual environment
      - ./logs:/app/logs # Bind mount logs directory
    environment:
      - ENV=development
    container_name: wea-app-dev
  db:
    container_name: wea-db-dev
