[project]
name = "WeaMind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12" # 影響 pyupgrade 自動修正的版本，替代 target-version
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.2.9",
    "pydantic-settings>=2.9.1",
    "sqlalchemy>=2.0.40",
    "uvicorn[standard]>=0.34.2",
]

[dependency-groups]
dev = [
    "alembic>=1.16.1",
    "pre-commit>=4.2.0",
    "pyright>=1.1.401",
    "ruff>=0.11.9",
]

[tool.ruff] # https://docs.astral.sh/ruff/settings/#top-level
line-length = 100
exclude = ["migrations", ".venv"]

[tool.ruff.lint] # https://docs.astral.sh/ruff/settings/#lint

select = ["E", "W", "F", "I", "UP"]

extend-select = [
  # ★ 全開 ANN / B / ASYNC / TRY / PERF ★
  "ANN",
  "B",
  "ASYNC",
  "TRY",
  "PERF",

  # FastAPI 專屬
  "FAST001", "FAST002",

  # Docstring 規則
  "D103", "DOC201",

  # 其他
  "S101", "S110", "ERA001",
]

# 針對雜訊高的規則做全域排除（示例）
ignore = [
  "E402", # module level import not at top of file
  "ANN101", # self / cls 無需標註
]

[tool.ruff.format] # https://docs.astral.sh/ruff/settings/#format
quote-style = "double" # 引號風格，雙引號是預設值
