"""feature/liff-location-settings_20250816_223619

Revision ID: 7f11c9b6d545
Revises: 69db147baaec
Create Date: 2025-08-16 14:36:19.804147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f11c9b6d545'
down_revision: Union[str, None] = '69db147baaec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('home_location_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('work_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'location', ['work_location_id'], ['id'])
    op.create_foreign_key(None, 'user', 'location', ['home_location_id'], ['id'])
    op.drop_index(op.f('ix_weather_location_fetched_at'), table_name='weather')
    op.drop_index(op.f('ix_weather_location_start_time'), table_name='weather')
    op.create_index(op.f('ix_weather_start_time'), 'weather', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_start_time'), table_name='weather')
    op.create_index(op.f('ix_weather_location_start_time'), 'weather', ['location_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_weather_location_fetched_at'), 'weather', ['location_id', 'fetched_at'], unique=False)
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'work_location_id')
    op.drop_column('user', 'home_location_id')
    # ### end Alembic commands ###
