"""Remove unused display_name column from user table

Revision ID: bcec2f9b0ea0
Revises: d2d7367827f4
Create Date: 2025-09-30 09:07:35.661944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcec2f9b0ea0'
down_revision: Union[str, None] = 'd2d7367827f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
