"""feature/user-query-history_20250824_232001

Revision ID: cdb5dd844b83
Revises: 7f11c9b6d545
Create Date: 2025-08-24 15:20:01.936084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb5dd844b83'
down_revision: Union[str, None] = '7f11c9b6d545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_query',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('query_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_query_query_time'), 'user_query', ['query_time'], unique=False)
    op.create_index(op.f('ix_user_query_user_id'), 'user_query', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_query_user_id'), table_name='user_query')
    op.drop_index(op.f('ix_user_query_query_time'), table_name='user_query')
    op.drop_table('user_query')
    # ### end Alembic commands ###
