"""remove_weather_created_updated_timestamps

Revision ID: d2d7367827f4
Revises: 8ef96c483fc9
Create Date: 2025-09-21 17:11:16.632361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2d7367827f4'
down_revision: Union[str, None] = '8ef96c483fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather', 'updated_at')
    op.drop_column('weather', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('weather', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    # ### end Alembic commands ###
