name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonar:
    runs-on: ubuntu-latest
    concurrency:
      group: sonar-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      - name: Generate sonar-project.properties
        run: |
          cat <<'EOF' > sonar-project.properties
          sonar.organization=kyomind
          sonar.projectKey=kyomind_WeaMind
          sonar.sources=app
          EOF

      # 已開啟自動掃描，不能同時執行這個步驟
      # - name: SonarCloud Scan
      #   uses: sonarsource/sonarqube-scan-action@v5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
